package effectinventory

// The event catalog is explicit authored data. The recorder call has no result,
// so the catalog deliberately claims append intent, not durable delivery.
const (
	eventClassObservationAPI        catalogRouteClassID = "event/observation/api"
	eventClassObservationCLI        catalogRouteClassID = "event/observation/cli"
	eventClassObservationController catalogRouteClassID = "event/observation/controller"
)

func knownEventCatalogClassID(id catalogRouteClassID) bool {
	switch id {
	case eventClassObservationAPI,
		eventClassObservationCLI,
		eventClassObservationController:
		return true
	default:
		return false
	}
}

var eventCatalogRouteClassSpecs = []eventCatalogRouteClassSpec{
	{ID: eventClassObservationAPI, ExecutingProcess: ProcessAPIInController},
	{ID: eventClassObservationCLI, ExecutingProcess: ProcessForegroundCLI},
	{ID: eventClassObservationController, ExecutingProcess: ProcessController},
}

var eventCatalogSiteSpecs = []eventCatalogSiteSpec{
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailSendJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailReplyJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doSuspendCity", File: "cmd/gc/cmd_suspend.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doSuspendCity", File: "cmd/gc/cmd_suspend.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doEventEmit", File: "cmd/gc/cmd_event_emit.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "cmdSessionKill", File: "cmd/gc/cmd_session.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailSendAllJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doHandoffRemote", File: "cmd/gc/cmd_handoff.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doConvoyLandJSON", File: "cmd/gc/cmd_convoy.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailMarkReadJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailReadWithJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doConvoyCloseJSON", File: "cmd/gc/cmd_convoy.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "createHandoffMail", File: "cmd/gc/cmd_handoff.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailDeleteManyJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailMarkUnreadJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailArchiveManyJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailDeleteSingleJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doRuntimeDrain", File: "cmd/gc/cmd_runtime_drain.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doHandoffWithOutcome", File: "cmd/gc/cmd_handoff.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailArchiveSingleJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "wrapWithCachingStore", File: "cmd/gc/api_state.go", ClosurePath: []int{1}, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "runControllerWithLease", File: "cmd/gc/controller.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "runControllerWithLease", File: "cmd/gc/controller.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doRuntimeUndrain", File: "cmd/gc/cmd_runtime_drain.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doMailArchiveSelectedJSON", File: "cmd/gc/cmd_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitSupervisorStarted", File: "cmd/gc/cmd_supervisor.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "hookEmitClaimRejected", File: "cmd/gc/cmd_hook_claim.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "autocloseConvoyIfComplete", File: "cmd/gc/cmd_convoy.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "controllerState", Function: "ResumeCity", File: "cmd/gc/api_state.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/api", Receiver: "", Function: "EmitTypedEvent", File: "internal/api/request_id.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "controllerState", Function: "SuspendCity", File: "cmd/gc/api_state.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitPostgresCredentialResolved", File: "cmd/gc/bd_env.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitWorkQueryFailure", File: "cmd/gc/work_query_failure.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "gracefulStopAllWithOwnership", File: "cmd/gc/controller.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "recordResetStallIfDue", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "requestSupervisorShutdown", File: "cmd/gc/cmd_supervisor.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doConvoyCheckAcrossStoresJSON", File: "cmd/gc/cmd_convoy.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doConvoyCreateWithOptionsJSON", File: "cmd/gc/cmd_convoy.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "announceClosedMolecule", File: "cmd/gc/molecule_autoclose.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "announceClosedMolecule", File: "cmd/gc/molecule_autoclose.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "doRuntimeRequestRestart", File: "cmd/gc/cmd_runtime_drain.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationCLI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "CityRuntime", Function: "reloadConfigTraced", File: "cmd/gc/city_runtime.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reapClosedBeadWorktrees", File: "cmd/gc/bead_worktree_reaper.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reapClosedBeadWorktrees", File: "cmd/gc/bead_worktree_reaper.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatch", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "recordFSPressureSkippedTickEvent", File: "cmd/gc/fs_pressure.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "commitStartFailure", File: "cmd/gc/session_lifecycle_parallel.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "convergenceEventEmitter", Function: "Emit", File: "cmd/gc/convergence_store.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "relaunchAgentForLaunchDrift", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/api", Receiver: "Server", Function: "recordMailEvent", File: "internal/api/handler_mail.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitProjectIdentityStampedEvent", File: "cmd/gc/dolt_project_id.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitProviderHealthGateAlert", File: "cmd/gc/provider_health_gate.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitSessionStrandedDiagnostic", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "recordManagedControllerStarted", File: "cmd/gc/cmd_supervisor.go", ClosurePath: []int{1}, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchOne", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchOne", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchExec", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchExec", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchExec", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 3, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchExec", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 4, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchExec", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 5, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 3, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 4, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 5, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 6, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 7, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 8, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "memoryOrderDispatcher", Function: "dispatchWisp", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 9, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "commitStartResultTraced", File: "cmd/gc/session_lifecycle_parallel.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitDeadAssigneeReopenedEvents", File: "cmd/gc/dead_assignee_event.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "recordDrainAckAssignedWorkEvent", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/api", Receiver: "Server", Function: "extmsgEmitEvent", File: "internal/api/handler_extmsg.go", ClosurePath: []int{2}, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "finalizeDrainAckStoppedSession", File: "cmd/gc/session_reconciler.go", ClosurePath: []int{1}, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/emergency", Receiver: "", Function: "recordEmergencyEvent", File: "internal/emergency/emergency.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/worker", Receiver: "", Function: "recordOperationEvent", File: "internal/worker/operation_events.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "emitSessionUnknownStateDiagnostic", File: "cmd/gc/session_reconciler.go", ClosurePath: []int{2}, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/api", Receiver: "Server", Function: "humaHandleEventEmit", File: "internal/api/huma_handlers_events.go", ClosurePath: []int{1}, Ordinal: 1, Class: eventClassObservationAPI},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "conditionalWritesDegradedRecorder", File: "cmd/gc/store_rollout.go", ClosurePath: []int{1}, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 3, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 4, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 5, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "reconcileSessionBeadsTracedWithNamedDemand", File: "cmd/gc/session_reconciler.go", ClosurePath: nil, Ordinal: 6, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "stopTargetsBoundedWithOwnershipAndBudget", File: "cmd/gc/session_lifecycle_parallel.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "stopTargetsBoundedWithOwnershipAndBudget", File: "cmd/gc/session_lifecycle_parallel.go", ClosurePath: nil, Ordinal: 2, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/supervisor", Receiver: "StoreMaintenanceLoop", Function: "emitRunEvent", File: "internal/supervisor/maintenance.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
	{BoundaryID: "events.recorder.Record", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/supervisor", Receiver: "StoreMaintenanceLoop", Function: "emitDiskEvent", File: "internal/supervisor/maintenance.go", ClosurePath: nil, Ordinal: 1, Class: eventClassObservationController},
}

// generated counts: 90 event sites, 3 semantic classes
