package effectinventory

// The process catalog is explicit authored data. Discovery verifies these rows;
// it never infers their classifications at runtime.
const (
	processClassBoundarySignalCLIOne          catalogRouteClassID = "process-boundary/signal/cli/one"
	processClassBoundarySignalCLISet          catalogRouteClassID = "process-boundary/signal/cli/set"
	processClassBoundarySignalControllerOne   catalogRouteClassID = "process-boundary/signal/controller/one"
	processClassBoundarySignalControllerSet   catalogRouteClassID = "process-boundary/signal/controller/set"
	processClassDirectSignalCLIOne            catalogRouteClassID = "direct-process-bypass/signal/cli/one"
	processClassDirectSignalControllerOne     catalogRouteClassID = "direct-process-bypass/signal/controller/one"
	processClassWorkspaceLiveConfigController catalogRouteClassID = "process-boundary/workspace/live-config/controller/set"
	processClassWorkspaceProvisionController  catalogRouteClassID = "process-boundary/workspace/runtime-provision/controller/set"
	processClassWorkspaceTeardownController   catalogRouteClassID = "process-boundary/workspace/server-teardown/controller/set"
	processClassWorkspaceRestartAPI           catalogRouteClassID = "process-boundary/workspace/runtime-launch/api/one"
)

func knownProcessCatalogClassID(id catalogRouteClassID) bool {
	switch id {
	case processClassBoundarySignalCLIOne,
		processClassBoundarySignalCLISet,
		processClassBoundarySignalControllerOne,
		processClassBoundarySignalControllerSet,
		processClassDirectSignalCLIOne,
		processClassDirectSignalControllerOne,
		processClassWorkspaceLiveConfigController,
		processClassWorkspaceProvisionController,
		processClassWorkspaceTeardownController,
		processClassWorkspaceRestartAPI:
		return true
	default:
		return false
	}
}

var processCatalogRouteClassSpecs = []processCatalogRouteClassSpec{
	{ID: processClassBoundarySignalCLIOne, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessForegroundCLI, AccessPath: AccessProcessBoundary, TargetShape: processTargetSingleParameter},
	{ID: processClassBoundarySignalCLISet, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessForegroundCLI, AccessPath: AccessProcessBoundary, TargetShape: processTargetSetParameter},
	{ID: processClassBoundarySignalControllerOne, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessController, AccessPath: AccessProcessBoundary, TargetShape: processTargetSingleParameter},
	{ID: processClassBoundarySignalControllerSet, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessController, AccessPath: AccessProcessBoundary, TargetShape: processTargetSetParameter},
	{ID: processClassDirectSignalCLIOne, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessForegroundCLI, AccessPath: AccessDirectProcessBypass, TargetShape: processTargetSingleReceiver, ReplacementGate: "P3.3"},
	{ID: processClassDirectSignalControllerOne, ActionFamily: FamilyProcessSignal, ExecutingProcess: ProcessController, AccessPath: AccessDirectProcessBypass, TargetShape: processTargetSingleReceiver, ReplacementGate: "P3.3"},
	{ID: processClassWorkspaceLiveConfigController, ActionFamily: FamilyLiveConfig, ExecutingProcess: ProcessController, AccessPath: AccessProcessBoundary, TargetShape: processTargetServerSetReceiver},
	{ID: processClassWorkspaceProvisionController, ActionFamily: FamilyRuntimeProvision, ExecutingProcess: ProcessController, AccessPath: AccessProcessBoundary, TargetShape: processTargetServerSetReceiver},
	{ID: processClassWorkspaceTeardownController, ActionFamily: FamilyServerTeardown, ExecutingProcess: ProcessController, AccessPath: AccessProcessBoundary, TargetShape: processTargetServerSetReceiver},
	{ID: processClassWorkspaceRestartAPI, ActionFamily: FamilyRuntimeLaunch, ExecutingProcess: ProcessAPIInController, AccessPath: AccessProcessBoundary, TargetShape: processTargetServerParameter},
}

var processCatalogSiteSpecs = []processCatalogSiteSpec{
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "waitForPIDExit", File: "cmd/gc/cmd_start_drift.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "killProcess", File: "cmd/gc/dolt_cleanup_discovery.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "defaultRestartHelpers", File: "cmd/gc/cmd_start_drift.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "stopManagedDoltProcessWithOptions", File: "cmd/gc/dolt_stop_managed.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "stopManagedDoltProcessWithOptions", File: "cmd/gc/dolt_stop_managed.go", ClosurePath: nil, Ordinal: 2, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/workspacesvc", Receiver: "", Function: "signalProcessOrGroup", File: "internal/workspacesvc/orphan_signal_windows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetWindows, Class: processClassBoundarySignalControllerOne},
	{BoundaryID: "pidutil.Signal", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/workspacesvc", Receiver: "", Function: "signalProcessOrGroup", File: "internal/workspacesvc/orphan_signal_notwindows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "ensureNudgePoller", File: "cmd/gc/cmd_nudge.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassDirectSignalCLIOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/beads", Receiver: "", Function: "killCommandTree", File: "internal/beads/exec_timeout_unix.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/events/exec", Receiver: "execWatcher", Function: "Close", File: "internal/events/exec/exec.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/beads", Receiver: "", Function: "killCommandTree", File: "internal/beads/exec_timeout_windows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetWindows, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/session", Receiver: "", Function: "ensureSessionSubmitPoller", File: "internal/session/submit.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/processgroup", Receiver: "", Function: "killDirect", File: "internal/processgroup/processgroup_unix.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "Provider", Function: "Start", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "Provider", Function: "Start", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 2, ProfileSet: processProfileSetAll, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/processgroup", Receiver: "", Function: "TerminateCommand", File: "internal/processgroup/processgroup_windows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetWindows, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "os.process.Kill", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/orders", Receiver: "", Function: "prepareConditionCommand", File: "internal/orders/trigger_exec_windows.go", ClosurePath: []int{1, 1}, Ordinal: 1, ProfileSet: processProfileSetWindows, Class: processClassDirectSignalControllerOne},
	{BoundaryID: "pidutil.SignalProcess", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/pidutil", Receiver: "", Function: "Signal", File: "internal/pidutil/pidutil.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerOne},
	{BoundaryID: "processgroup.Terminate", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "terminateProcessGroup", File: "cmd/gc/cmd_supervisor_lifecycle.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.Terminate", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/processgroup", Receiver: "", Function: "TerminateCommand", File: "internal/processgroup/processgroup_unix.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "processgroup.SignalGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/beads", Receiver: "", Function: "killCommandTree", File: "internal/beads/exec_timeout_unix.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "processgroup.SignalGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "terminateManagedDoltTestProcessGroup", File: "cmd/gc/dolt_process_group_notwindows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "terminateManagedDoltTestProcessGroup", File: "cmd/gc/dolt_process_group_notwindows.go", ClosurePath: nil, Ordinal: 2, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/workspacesvc", Receiver: "", Function: "signalProcessOrGroup", File: "internal/workspacesvc/orphan_signal_notwindows.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "workspacesvc.manager.Tick", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "CityRuntime", Function: "tick", File: "cmd/gc/city_runtime.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassWorkspaceProvisionController},
	{BoundaryID: "processgroup.SignalCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "lsofOutput", File: "cmd/gc/dolt_process_inspection.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "processArgsFromPS", File: "cmd/gc/dolt_process_inspection.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "fileOpenedByAnyProcess", File: "cmd/gc/dolt_preflight_cleanup.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "prepareProviderOpCommand", File: "cmd/gc/provider_op_process_unix.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalCLISet},
	{BoundaryID: "processgroup.SignalCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "prepareProviderOpCommand", File: "cmd/gc/provider_op_process_windows.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetWindows, Class: processClassBoundarySignalCLIOne},
	{BoundaryID: "workspacesvc.manager.Close", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "CityRuntime", Function: "shutdown", File: "cmd/gc/city_runtime.go", ClosurePath: []int{1}, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassWorkspaceTeardownController},
	{BoundaryID: "runtime.proctable.KillByPID", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/tmux", Receiver: "Provider", Function: "TerminateRuntime", File: "internal/runtime/tmux/adapter.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.proctable.KillByPID", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "Provider", Function: "TerminateRuntime", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "workspacesvc.manager.Reload", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "newCityRuntime", File: "cmd/gc/city_runtime.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassWorkspaceLiveConfigController},
	{BoundaryID: "workspacesvc.manager.Reload", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "CityRuntime", Function: "reloadConfigTraced", File: "cmd/gc/city_runtime.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassWorkspaceLiveConfigController},
	{BoundaryID: "processgroup.TerminateCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/cmd/gc", Receiver: "", Function: "cancelShellExecProcessGroup", File: "cmd/gc/order_dispatch.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "processgroup.TerminateCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/workspacesvc", Receiver: "", Function: "stopProcessGroup", File: "internal/workspacesvc/proxy_process.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "processgroup.TerminateCommand", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/orders", Receiver: "", Function: "prepareConditionCommand", File: "internal/orders/trigger_exec_unix.go", ClosurePath: []int{1, 1}, Ordinal: 1, ProfileSet: processProfileSetUnix, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "workspacesvc.registry.Restart", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/api", Receiver: "Server", Function: "humaHandleServiceRestart", File: "internal/api/huma_handlers_services.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassWorkspaceRestartAPI},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "Provider", Function: "Start", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "Provider", Function: "Start", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 2, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "Provider", Function: "Start", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 3, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "Provider", Function: "Interrupt", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "", Function: "handleControlConn", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime", Receiver: "", Function: "TerminateManagedProcess", File: "internal/runtime/process_control.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime", Receiver: "", Function: "TerminateManagedProcess", File: "internal/runtime/process_control.go", ClosurePath: nil, Ordinal: 2, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "Provider", Function: "Interrupt", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.SignalProcessGroup", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "", Function: "handleSessionConn", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.TerminateManagedProcess", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "", Function: "terminateProcess", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.TerminateManagedProcess", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/acp", Receiver: "", Function: "handleControlConn", File: "internal/runtime/acp/acp.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.TerminateManagedProcess", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "", Function: "handleSessionConn", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
	{BoundaryID: "runtime.process.TerminateManagedProcess", Operation: OperationCall, Package: "github.com/gastownhall/gascity/internal/runtime/subprocess", Receiver: "", Function: "terminateSessionConn", File: "internal/runtime/subprocess/subprocess.go", ClosurePath: nil, Ordinal: 1, ProfileSet: processProfileSetAll, Class: processClassBoundarySignalControllerSet},
}

// generated counts: 52 process sites, 10 semantic classes
