package effectinventory

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"testing"
)

// updateGolden regenerates testdata/inventory_golden.json instead of asserting
// against it. Run: go test ./internal/reconciletest/effectinventory/ -run Golden
// -update-effect-golden
var updateGolden = flag.Bool("update-effect-golden", false, "regenerate the effect-inventory golden file")

func goldenPath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	return filepath.Join(filepath.Dir(thisFile), "testdata", "inventory_golden.json")
}

func discoverCanonical(t *testing.T) []DiscoveredSite {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	repoRoot, modulePath, err := RepoRootFromDir(filepath.Dir(thisFile))
	if err != nil {
		t.Fatalf("RepoRootFromDir: %v", err)
	}
	sites, err := Discover(context.Background(), DiscoverConfig{
		RepoRoot:   repoRoot,
		ModulePath: modulePath,
		Profiles:   CanonicalProfiles(),
		Boundaries: canonicalBoundaries(),
	})
	if err != nil {
		t.Fatalf("Discover: %v", err)
	}
	return sites
}

// TestCanonicalInventoryGolden is the "counts are generated by a Go/AST test /
// no unknown site" gate: the discovered set must exactly match the pinned
// golden, with zero added or removed sites.
func TestCanonicalInventoryGolden(t *testing.T) {
	sites := discoverCanonical(t)
	path := goldenPath(t)

	if *updateGolden {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		blob, err := json.MarshalIndent(sites, "", "  ")
		if err != nil {
			t.Fatalf("marshal golden: %v", err)
		}
		if err := os.WriteFile(path, append(blob, '\n'), 0o644); err != nil {
			t.Fatalf("write golden: %v", err)
		}
		t.Logf("wrote %d sites to %s", len(sites), path)
		return
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read golden (regenerate with -update-effect-golden): %v", err)
	}
	var want []DiscoveredSite
	if err := json.Unmarshal(data, &want); err != nil {
		t.Fatalf("unmarshal golden: %v", err)
	}

	assertNoInventoryDrift(t, want, sites)
	assertBoundaryTotals(t, want, sites)

	if len(sites) != len(want) {
		t.Errorf("total site count drift: golden=%d discovered=%d", len(want), len(sites))
	}
}

func inventorySiteKey(site DiscoveredSite) string {
	return site.BoundaryID + "\x00" + site.Matcher.key()
}

func describeSite(site DiscoveredSite) string {
	enclosing := site.Matcher.Enclosing.Object
	recv := enclosing.Receiver
	if recv != "" {
		recv = "(" + recv + ")."
	}
	return fmt.Sprintf("%s in %s.%s%s [%s ord=%d recv=%s viaIface=%t]",
		site.BoundaryID, enclosing.Package, recv, enclosing.Name,
		site.Matcher.Enclosing.File, site.Matcher.Ordinal, site.ReceiverType, site.ViaInterface)
}

func assertNoInventoryDrift(t *testing.T, want, got []DiscoveredSite) {
	t.Helper()
	wantByKey := make(map[string]DiscoveredSite, len(want))
	for _, site := range want {
		wantByKey[inventorySiteKey(site)] = site
	}
	gotByKey := make(map[string]DiscoveredSite, len(got))
	for _, site := range got {
		gotByKey[inventorySiteKey(site)] = site
	}

	var added, removed []string
	for key, site := range gotByKey {
		if _, ok := wantByKey[key]; !ok {
			added = append(added, describeSite(site))
		}
	}
	for key, site := range wantByKey {
		if _, ok := gotByKey[key]; !ok {
			removed = append(removed, describeSite(site))
		}
	}
	sort.Strings(added)
	sort.Strings(removed)

	if len(added) > 0 {
		t.Errorf("%d effect site(s) ADDED vs golden (unknown new boundary crossings — review, then regenerate with -update-effect-golden):\n  + %s",
			len(added), strings.Join(added, "\n  + "))
	}
	if len(removed) > 0 {
		t.Errorf("%d effect site(s) REMOVED vs golden (a boundary crossing disappeared — confirm intended, then regenerate):\n  - %s",
			len(removed), strings.Join(removed, "\n  - "))
	}
}

func assertBoundaryTotals(t *testing.T, want, got []DiscoveredSite) {
	t.Helper()
	countByBoundary := func(sites []DiscoveredSite) map[string]int {
		counts := map[string]int{}
		for _, site := range sites {
			counts[site.BoundaryID]++
		}
		return counts
	}
	wantCounts := countByBoundary(want)
	gotCounts := countByBoundary(got)

	ids := map[string]bool{}
	for id := range wantCounts {
		ids[id] = true
	}
	for id := range gotCounts {
		ids[id] = true
	}
	ordered := make([]string, 0, len(ids))
	for id := range ids {
		ordered = append(ordered, id)
	}
	sort.Strings(ordered)
	for _, id := range ordered {
		if wantCounts[id] != gotCounts[id] {
			t.Errorf("boundary %q count drift: golden=%d discovered=%d", id, wantCounts[id], gotCounts[id])
		}
	}
}
